qr_gen_project/accounts/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



app_name = 'accounts'
urlpatterns = [
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html', ), name='password_reset_done', ),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), name='password_reset_confirm'),
]

urlpatterns += [

    path('', views.index, name="index"),
    path('register/',views.register, name="register"),
    path('login/',views.login_view, name="login"),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('dashboard/',views.dashboard, name="dashboard"),
    path('faq/', views.faq, name="faq"), # avong added thisn for FAQ page
]

qr_gen_project/api/urls.py
from django.urls import include, path,re_path
from api import views


urlpatterns = [
    path('register/', views.RegisterAPIView.as_view(), name = 'register'),
    path('login/', views.LoginAPIView.as_view(), name = 'login'),
    path('user/', views.AuthUserAPIView.as_view(), name = 'user'),
]

urlpatterns += [
    path('<str:category>', views.QRCategoryView.as_view(), name='qr_category'), # Fetch all user QR from a category
    path('<str:category>/<int:pk>', views.QROneCategoryView.as_view(), name='get_one'), # Fetch one user QR from a category
    path('', views.QRAPIView.as_view(), name='all_user_qr'), # Fetch all user QR
]

# Coming soon ...
# urlpatterns = [
#     path('<int:id>/delete', views.DeleteQRAPIView.as_view(), name='delete_one'), # Delete One user QR from a category    
#     path('<int:id>/category/create/', views), # Create a new QR in a category ... coming soon
#     path('<int:id>/category/edit/', views), # edit a QR in a category ... coming soon
#     path('<int:id>/<str:category/delete', views.), # Delete all user QR from a category
#     path('<str:category>/<int:id>/delete', views.DeleteQRAPIView.as_view(), name='delete_one'), # Delete One user QR from a category
#     path('<int:id>/delete', views.), # Delete all user QR from all categories
# ]

qr_gen_project/qr_gen_project/urls.py
# qr_gen_project/settings.py

from re import M
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


from django.contrib.auth import views as auth_views

schema_view = get_schema_view(
   openapi.Info(
      title="QR Planets API Documentation",
      default_version='v1',
      description="""The Easiest Way to generate, download &amp; share QR Codes Online with QR Planet Code Generator within few minutes.
      Get started today.
      These are the Available Endpoints, Other API Endpoints are coming soon""",
      
      contact=openapi.Contact(email="simplenick01@gmail.com"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
   authentication_classes=[]
)


urlpatterns = [
   path('qr-gen/api/documentation/', schema_view.with_ui('swagger', cache_timeout=0), name='docs'),
   path('qr-gen/api/redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
   path('qr-gen/api/', include('api.urls'), ),
]

urlpatterns += [
    path('qr-gen/', include('qr_generator.urls', namespace='qr_generator'),),
    path('qr-gen/admin/', admin.site.urls),
]

urlpatterns += [
    path('qr-gen/accounts/', include('accounts.urls', namespace='accounts'),),
]

urlpatterns +=[
    path('reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),      
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "qr_generator.views.page_not_found"

qr_gen_project/qr_generator/urls.py
from django.urls import path
from qr_generator import views


app_name = 'qr_generator'

urlpatterns = [
    path('', views.index, name="home"),
]

urlpatterns += [
    path('generate-qr/', views.generate_qr, name='generate_qr'),
    path('share-qr/<str:pk>/', views.share_qr, name='share'),
    path('download-qr/<str:id>/<str:file_type>/', views.download_file, name='download'),
    path('save-qr/<str:id>/', views.save_qr, name='save_qr'),
]

urlpatterns +=[
    path('contact-us/', views.contact_us, name='contact'),
    path('learn-more/', views.learn_more, name="learn_more"), 
]

qr_gen_project/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  
  <head>
    {% block head %}
    <!-- This Head tags are for SEO -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="canonical" href="http://qr-gen/" />
    <!--! Change Later -->
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="keywords" content="qr code generator" />
    <meta name="description" content="The Easiest Way to generate, download &amp; share QR Codes
        Online with QR Planet Code Generator within few minutes. Get started today."/>
    <meta content="yes" name="apple-mobile-web-app-capable" />
    <meta itemprop="description" content="Quickly Generate, Download and Share QR Codes!"/>
    <link rel="icon" sizes="192x192" href="{% static 'base/favicon_io/android-chrome-192x192.png' %}"/>
    <link rel="apple-touch-icon" type="image/png" href="{% static 'base/favicon_io/apple-touch-icon.png' %}"/>
    <link rel="icon" type="image/png" sizes="512x512" href="{% static 'base/favicon_io/android-chrome-512x512.png' %}"/>
    <link rel="shortcut icon" href="{% static 'base/favicon_io/favicon.ico' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'base/css/base.css'%}">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
  />
  <link
    rel="stylesheet"
    href="https://unicons.iconscout.com/release/v2.1.5/css/unicons.css"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  />
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  
  <title>QR&nbsp;Planet&nbsp;{% block title %} {% endblock title %}</title>

    {% block style %} {% endblock style %}
    {% endblock head %}
  </head>
  <body>
    {% if messages %}
      {% include 'base/messages.html' %}
    {% endif%}
    <header>      
      {% block header %} {% endblock header %}
    </header>

    {% block content %} {% endblock content %}
    

    <footer>
        {% block top_footer %}{% endblock top_footer %}
        {% block middle_footer %}{% endblock middle_footer %}
        {% block bottom_footer %}{% endblock bottom_footer %}
    </footer>


       {% block extra_script %}{% endblock extra_script %} 

    
    {# messages everywhere#}

    <script>
      var message = document.getElementById("message_div");

      setTimeout(function(){ 
        message.style.display = "none"; 
      }, 3000);
      // Timeout is 3 sec,
    </script>
</html>

qr_gen_project/templates/base/bottom_footer.html
{% load static %}


{% block bottom_footer %} 
<div class="bottom_footer">
    <div class="wrapper">
        <div class="footer_2">
            <p><span>2022</span> QR Planet; All Rights Reserved</p>
            <a href="{% url 'qr_generator:contact'%}">Report</a>
        </div>
    </div>

</div>

{% endblock bottom_footer %} 

qr_gen_project/templates/base/coming_soon.html
{% extends 'qr_generator/index.html'%}
{% load static %}

{% block style%}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'base/css/coming_soon.css'%}">
{% endblock style%}

{% block title %} {{ block.super }}&nbsp;&#124;&nbsp;Coming&nbsp;Soon&nbsp;{% endblock title %}

{% block content%}
<div class="container">
    <div class="text">
      <h1>Coming Soon...</h1>
      <p>We are working on making more features available.</p>
</div>
{% endblock content%}

{% block top_footer %}{% endblock top_footer %}
{% block middle_footer %}{% endblock middle_footer %}
{% block bottom_footer %}{% endblock bottom_footer %}

qr_gen_project/templates/base/error404.html
{% extends 'qr_generator/index.html'%}
{% load static %}


{% block title %}Error{% endblock title %}

{% block content%}
    <section class="middle-section">
        <div class="error">
          <img src="{% static 'base/images/error.svg' %}" alt="" />
          <h1>Oops! Something went wrong.</h1>
        </div>
      </section>

{% endblock content%}

     
{% block middle_footer %}{% endblock middle_footer %}
     

qr_gen_project/templates/base/header.html
{% load static %}


{% block header %} 
<div class="wrapper"><a href="{% url 'qr_generator:home'%}">
    <img class="logo" href="{% url 'qr_generator:home'%}" src="{% static 'qr_generator/images/logo.svg'%}" alt="logo" />
  </a>
    <nav class="navbar">
      <input type="checkbox" name="" id="nav-toggle">
      <div class="nav-links">
        <ul>
          <li><a href="{% url 'qr_generator:home'%}">Home</a></li>
          <li><a href="{% url 'qr_generator:generate_qr' %}">Generate QR Code</a></li>
          <li><a href="#">Why us?</a></li>
          <li><a href="{% url 'docs'%}">API</a></li>
          <li><a href="{% url 'qr_generator:contact'%}">Contact</a></li>
        </ul>
        <div class="nav-button">
            {% if request.user.is_authenticated %}
                <button type = "submit" class="Secondary-button"><a href="{% url 'accounts:logout'%}">Logout</a></button>
                <button type = "submit" class="Primary-button"><a href="#">Dashboard</a></button>
            {% else %}
                <button type = "submit" class="Secondary-button"><a href="{% url 'accounts:login'%}">Login</a></button>
                <button type = "submit" class="Primary-button"><a href="{% url 'qr_generator:generate_qr' %}">Get Started</a></button>
                
            {% endif %}
            
          
        </div>
      </div>            
      <label for="nav-toggle" class="icon-burger"> 
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div> 
      </label>  
    </nav>
  </div> 
{% endblock header %}

qr_gen_project/templates/base/messages.html
{% load static %}


{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert" id="message_div">
  <strong>{{message}}</strong> 
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}

qr_gen_project/templates/base/middle_footer.html
{% load static %}

        
{% block middle_footer %} 
<div class="middle_footer">
    <div class="wrapper">
        <div class="md_footer_info">
            <p>Enjoy seamless and efficient generation of qr <br> codes. Create various styles for your qr codes using <br> the various designs available</p>
        </div>

        <div class="footer_info">
            <p>QR Planet</p>
            <ul>
                <li><a href="#">How to generate QR codes</a></li>
                <li><a href="#">Dynamic QR codes</a></li>
                <li><a href="#"></a>Static QR codes</li>
            </ul>
        </div>

          <div class="footer_info">
            <p>Why us?</p>
            <ul>
                <li><a href="#">Product features</a></li>
                <li><a href="#">About us</a></li>
                <li><a href="#"></a>FAQs</li>
            </ul>
        </div>

          <div class="footer_info">
            <p>API</p>
            <ul>
                <li><a href="#">API docs</a></li>
            </ul>
        </div>

          <div class="footer_info">
            <p>Contact</p>
            <a href="https://twitter.com/SimpleNick6"><img src="{% static 'qr_generator/images/Twitter.png'%}" alt="Twitter" height="24px"/></a>
            <img src="{% static 'qr_generator/images/Facebook.png'%}" alt="Facebook" height="24px" />
            <img src="{% static 'qr_generator/images/Linkedin.png'%}" alt="Linkedin" height="24px" />                    
        </div>            
    </div>  
</div>
{% endblock middle_footer %}

qr_gen_project/templates/base/top_and_middle_footer.html
{% load static %}

{% block top_and_middle_footer %} 
<div class="top_footer">
    <div class="wrapper">
        <div class="">
            <h4>Don't miss out!</h4>
            <p>Do you like discounts, specials offers and rewards?</p>
        </div>
        <form>
            <input type="email" class="mail" placeholder="Email" name="" id="">
            <button type="submit" class="footer-button"> <a href="#"> Subscribe Now</a></button>
        </form>
    </div>
</div>        
<hr>

<div class="middle_footer">
    <div class="wrapper">
        <div class="md_footer_info">
            <p>Enjoy seamless and efficient generation of qr <br> codes. Create various styles for your qr codes using <br> the various designs available</p>
        </div>

        <div class="footer_info">
            <p>QR Planet</p>
            <ul>
                <li><a href="#">How to generate QR codes</a></li>
                <li><a href="#">Dynamic QR codes</a></li>
                <li><a href="#"></a>Static QR codes</li>
            </ul>
        </div>

          <div class="footer_info">
            <p>Why us?</p>
            <ul>
                <li><a href="#">Product features</a></li>
                <li><a href="#">About us</a></li>
                <li><a href="#"></a>FAQs</li>
            </ul>
        </div>

          <div class="footer_info">
            <p>API</p>
            <ul>
                <li><a href="#">API docs</a></li>
            </ul>
        </div>

          <div class="footer_info">
            <p>Contact</p>
            <img src="{% static 'qr_generator/images/Twitter.png'%}" alt="Twitter" height="24px"/>
            <img src="{% static 'qr_generator/images/Facebook.png'%}" alt="Facebook" height="24px" />
            <img src="{% static 'qr_generator/images/Linkedin.png'%}" alt="Linkedin" height="24px" />                    
        </div>            
    </div>  
</div>
{% endblock top_and_middle_footer %}

qr_gen_project/templates/base/top_footer.html
{% load static %}


{% block top_footer %} 
<div class="top_footer">
    <div class="wrapper">
        <div class="">
            <h4>Don't miss out!</h4>
            <p>Do you like discounts, specials offers and rewards?</p>
        </div>
        <form>
            <input type="email" class="mail" placeholder="Email" name="" id="">
            <button type="submit" class="footer-button"> <a href="#"> Yes Please</a></button>
        </form>
    </div>
</div>
<hr>
{% endblock top_footer %}  