qr_gen_project/api/urls.py
from django.urls import include, path,re_path
from api import views


urlpatterns = [
    path('register/', views.RegisterAPIView.as_view(), name = 'register'),
    path('login/', views.LoginAPIView.as_view(), name = 'login'),
    path('user/', views.AuthUserAPIView.as_view(), name = 'user'),
]

urlpatterns += [
    path('<str:category>', views.QRCategoryView.as_view(), name='qr_category'), # Fetch all user QR from a category
    path('<str:category>/<int:pk>', views.QROneCategoryView.as_view(), name='get_one'), # Fetch one user QR from a category
    path('', views.QRAPIView.as_view(), name='all_user_qr'), # Fetch all user QR
]

# Coming soon ...
# urlpatterns = [
#     path('<int:id>/delete', views.DeleteQRAPIView.as_view(), name='delete_one'), # Delete One user QR from a category    
#     path('<int:id>/category/create/', views), # Create a new QR in a category ... coming soon
#     path('<int:id>/category/edit/', views), # edit a QR in a category ... coming soon
#     path('<int:id>/<str:category/delete', views.), # Delete all user QR from a category
#     path('<str:category>/<int:id>/delete', views.DeleteQRAPIView.as_view(), name='delete_one'), # Delete One user QR from a category
#     path('<int:id>/delete', views.), # Delete all user QR from all categories
# ]

qr_gen_project/qr_gen_project/urls.py
# qr_gen_project/settings.py

from re import M
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


from django.contrib.auth import views as auth_views

schema_view = get_schema_view(
   openapi.Info(
      title="QR Planets API Documentation",
      default_version='v1',
      description="""The Easiest Way to generate, download &amp; share QR Codes Online with QR Planet Code Generator within few minutes.
      Get started today.
      These are the Available Endpoints, Other API Endpoints are coming soon""",
      
      contact=openapi.Contact(email="simplenick01@gmail.com"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
   authentication_classes=[]
)


urlpatterns = [
   path('qr-gen/api/documentation/', schema_view.with_ui('swagger', cache_timeout=0), name='docs'),
   path('qr-gen/api/redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
   path('qr-gen/api/', include('api.urls'), ),
]

urlpatterns += [
    path('qr-gen/', include('qr_generator.urls', namespace='qr_generator'),),
    path('qr-gen/admin/', admin.site.urls),
]

urlpatterns += [
    path('qr-gen/accounts/', include('accounts.urls', namespace='accounts'),),
]

urlpatterns +=[
    path('reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),      
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "qr_generator.views.page_not_found"

qr_gen_project/qr_generator/urls.py
from django.urls import path
from qr_generator import views


app_name = 'qr_generator'

urlpatterns = [
    path('', views.index, name="home"),
]

urlpatterns += [
    path('generate-qr/', views.generate_qr, name='generate_qr'),
    path('share-qr/<str:pk>/', views.share_qr, name='share'),
    path('download-qr/<str:id>/<str:file_type>/', views.download_file, name='download'),
    path('save-qr/<str:id>/', views.save_qr, name='save_qr'),
]

urlpatterns +=[
    path('contact-us/', views.contact_us, name='contact'),
    path('learn-more/', views.learn_more, name="learn_more"), 
]

qr_gen_project/qr_generator/models.py
# account/models.py
from io import BytesIO
from qrcode import *
import qrcode
from django.utils import timezone
from django.core.files import File
from django.db import models
from django.contrib.auth import get_user_model
from qr_gen_project.settings import MEDIA_URL, STATIC_ROOT, STATIC_URL, MEDIA_ROOT


from django.db import models
import qrcode
from PIL import Image, ImageDraw
from io import BytesIO
from django.core.files import File
OUR_LOGO = STATIC_ROOT + '/base/images/' + 'qr_logo.png'
# Create your models here.
import random
import datetime



# Todo: extend the base user model and override to __str__ method to return name
User = get_user_model()


def get_current_time():
    now = str(datetime.datetime.now()).split('.')
    return str(now[1])


class Category(models.Model):
    """Every Available category"""
    category_name = models.CharField(primary_key=True, max_length=250, unique=True)

    def __str__(self):
        return f'{self.category_name}'

    class Meta:
        db_table = 'category'
        verbose_name_plural = 'categories'


class QRCollection(models.Model):
    """All QR collections available"""
    qr_user = models.ForeignKey(User, on_delete=models.CASCADE, )
    category = models.CharField(max_length=200, blank=True, null=True)
    time_created = models.DateTimeField(auto_now_add=True)
    
    qr_code = models.ImageField(upload_to='all_qr/')
    qr_info = models.CharField(max_length=200, blank=True, null=True)

    def save(self,*args,**kwargs):
        our_logo = Image.open(OUR_LOGO)
    
        # adjust image size
        widthpercent = (100/float(our_logo.size[0]))
        hsize = int((float(our_logo.size[1])*float(widthpercent)))
        our_logo = our_logo.resize((100, hsize), Image.ANTIALIAS)

        QRcode = qrcode.QRCode(
        version=3,
        box_size = 10,
        border=2,
        error_correction=qrcode.constants.ERROR_CORRECT_M
        )
        QRcode.add_data(self.qr_info)
        QRcode.make(fit=True)
    
        QRimg = QRcode.make_image(
            fill_color='black', back_color="white").convert('RGB')

         # set size of QR code
        pos = (
            (QRimg.size[0] - our_logo.size[0]) // 2,
            (QRimg.size[1] - our_logo.size[1]) // 2
            )

        QRimg.paste(our_logo, pos)
        buffer=BytesIO()
        QRimg.save(buffer, 'PNG')
        self.qr_code.save(f'{self.qr_user.username}{random.randint(0,9999)}.png',File(buffer),save=False)
        print(self.qr_code)
        super().save(*args,**kwargs)

    def __str__(self):
        return f'{self.qr_user.username}\'s {self.category}'


    class Meta:
        db_table = 'qr_collection'
        verbose_name_plural = 'qr_collections'

class UserCollection(models.Model):
    """A simple abstraction of the Collections for a user"""
    qr_user = models.ForeignKey(User, on_delete=models.CASCADE,)
    qr_code = models.IntegerField()

    def __str__(self):
        return str(self.qr_user)

    class Meta:
        db_table = 'user_collection'
        verbose_name_plural = 'user_collections'




# delete This
class MyQRCode(models.Model):
   url=models.URLField()
   image=models.ImageField(upload_to='qrcode',blank=True)
   user = models.CharField(max_length=200, blank=True, null=True)

   def save(self,*args,**kwargs):
        our_logo = Image.open(OUR_LOGO)
        # adjust image size
        widthpercent = (100/float(our_logo.size[0]))
        hsize = int((float(our_logo.size[1])*float(widthpercent)))
        our_logo = our_logo.resize((100, hsize), Image.ANTIALIAS)

        QRcode = qrcode.QRCode(
        version=3,
        box_size = 10,
        border=2,
        error_correction=qrcode.constants.ERROR_CORRECT_M
        )

        QRcode.make(fit=True)
    
        QRimg = QRcode.make_image(
            fill_color='black', back_color="white").convert('RGB')

         # set size of QR code
        pos = (
            (QRimg.size[0] - our_logo.size[0]) // 2,
            (QRimg.size[1] - our_logo.size[1]) // 2
            )

        QRimg.paste(our_logo, pos)

        canvas=Image.new("RGB", (300,300),"white")
        draw=ImageDraw.Draw(canvas)
        canvas.paste(QRimg)

        buffer=BytesIO()
        canvas.save(buffer,"PNG")
        self.image.save(f'{self.user}{random.randint(0,9999)}.png',File(buffer),save=False)
        canvas.close()
        super().save(*args,**kwargs)

qr_gen_project/qr_generator/forms.py
from django import forms


class ContactUsForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder':'Username',
                'required':True,
                'name':'name',
                'type':'text',
                'id':'required'
                }
                ))


    email = forms.CharField(
        widget = forms.TextInput(
                attrs={
                    'placeholder':'Email',
                    'required':True,
                    'id':'required',
                    'type':'email',
                    'name':'email',
                }
            ))

    subject = forms.CharField(
        widget = forms.TextInput(
                attrs={
                    'placeholder':'Subject of Mail',
                    'required':True,
                    'id':'required',
                    'type':'text',

                }
                ))

    message = forms.CharField(
        widget = forms.Textarea(
                attrs={
                    'placeholder':'Enter your message',
                    'required':True,
                    'id':'required',
                    'name':'message',
            })
        )

qr_gen_project/qr_generator/views.py
# account/views.py
import base64
from pathlib import Path
from pickletools import read_unicodestring1
from smtplib import SMTPServerDisconnected
from django.http import BadHeaderError, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.conf import settings

from django.core.mail import send_mail
from django.contrib import messages

from qr_generator.forms import ContactUsForm 
import qrcode
from PIL import Image
from django.conf import settings
from qr_gen_project.settings import  MEDIA_ROOT
import datetime
from django.contrib.auth.decorators import login_required

from django.contrib.auth import get_user_model

# --------------------imports

from django.shortcuts import render
from django.conf import settings
from qrcode import *
from .models import QRCollection, UserCollection


import mimetypes
import os
from django.http.response import HttpResponse
from django.shortcuts import render
import qrcode

import qrcode.image.svg

User = get_user_model()

def index(request):
    context = {}
    return render(request, 'qr_generator/index.html', context)



def share_qr(request, pk):
    return render(request, 'qr_generator/share_qr.html', {'qr_image':pk})


# =========== CONVERT QR FORMATS ================

# Convert to JPEG
def convert_to_jpeg(path):
    image = Image.open(path)
    rgb_image = image.convert('RGB')
    jpeg_image = rgb_image.save(path.replace('.png', '.jpeg'), 'JPEG')
    return path.replace('.png', '.jpeg'), os.path.basename(path.replace('.png', '.jpeg'))

def convert_to_png(path):
    image = Image.open(path)
    rgb_image = image.convert('RGB')
    png_image = rgb_image.save(path.replace('.png', '.png'), 'PNG')
    return path.replace('.png', '.png'), os.path.basename(path.replace('.png', '.png'))

# Convert to JPG
def convert_to_jpg(path):
    image = Image.open(path)
    rgb_image = image.convert('RGB')
    jpg_image = rgb_image.save(path.replace('.png', '.jpg'), 'JPG')
    return path.replace('.png', '.jpg'), os.path.basename(path.replace('.png', '.jpg'))


# Convert to SVG
def convert_to_svg(path):
    startSvgTag = """<?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
    "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    width="240px" height="240px" viewBox="0 0 240 240">"""
    endSvgTag = """</svg>"""
    pngFile = open(path, 'rb')
    base64data = base64.b64encode(pngFile.read())
    base64String = '<image xlink:href="data:image/png;base64,{0}" width="240" height="240" x="0" y="0" />'.format(base64data.decode('utf-8'))
    f = open(path.replace('.png', '.svg'), 'w')
    f.write(startSvgTag + base64String + endSvgTag)
    f.close()
    return path.replace('.png', '.svg'), os.path.basename(path.replace('.png', '.svg'))


# Convert to PDF
def convert_to_pdf(path):
    image = Image.open(path)
    rgb_image = image.convert('RGB')
    pdf_image = rgb_image.save(path.replace('.png', '.pdf'), 'PDF')
    return path.replace('.png', '.pdf'), os.path.basename(path.replace('.png', '.pdf'))

# =========== ENDCONVERT QR FORMATS ================


@login_required(login_url="/qr-gen/accounts/login")
def generate_qr(request):
    context = {}
    template = 'qr_generator/generateqr.html'
    
    if request.method == 'POST':

        # if text is selected        
        if 'text' in request.POST:
            QRCollection.objects.create(
                qr_user = request.user,
                category = 'TEXT',
                qr_info = 'Your Text is: ' + request.POST['text'],
                )

            ls = QRCollection.objects.all().order_by('-id')[0]
            context = {'qr_image':ls}

            return render(request, 'qr_generator/common/url_qr.html', context)

        # if Url is selected
        elif 'url-link' in request.POST:
            QRCollection.objects.create(
                qr_user = request.user,
                category = 'URL',
                qr_info = 'Your Link is: ' + request.POST['url-link'],
                )

            ls = QRCollection.objects.all().order_by('-id')[0]
            context = {'qr_image':ls}

            return render(request, 'qr_generator/common/url_qr.html', context)


        # if App-store is selected
        elif 'app-store' in request.POST:
            QRCollection.objects.create(
                qr_user = request.user,
                category = 'URL',
                qr_info = 'Your App-store Link is: ' + request.POST['app'],
                )

            ls = QRCollection.objects.all().order_by('-id')[0]
            context = {'qr_image':ls}

            return render(request, 'qr_generator/common/url_qr.html', context)
    
    return render(request, template, context)


def category(request, pk):
    if pk == "image":
        return 'image'

def save_qr(request, id):
    user = request.user
    UserCollection.objects.create(qr_user=user, qr_code=id)
    print('saved')
    messages.success(request, 'Your QR has been saved!! Go to You Dashboard to view it')
    return  render(request, 'qr_generator/generateqr.html')

def form(request, template):
    form = ContactUsForm()
    return render(request, "qr_generator/" + template +'.html', {"form":form})


def contact_us(request):
 
    context = {}
    if request.method == "POST":
        form =  ContactUsForm(request.POST)
        if form.is_valid():
            from_email = settings.QR_EMAIL_HOST_USER
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message'] #request.POST.get('message')
            reciever = settings.QR_EMAIL_HOST_USER

            try:
                send_mail(subject, message, from_email, [reciever,])
                messages.success(request, message="Message Successfully sent!!")
                return redirect('qr_generator:home')
            except BadHeaderError:
                messages.error(request, message="Invalid Header")
                return HttpResponse('Invalid header found.')

            except SMTPServerDisconnected:
                messages.error(request, message="Network Connection failed")
                return redirect(to='qr_generator:contact')

            except Exception as err:
                return HttpResponse("We haven't encountered this problem before") # TODO: will fix this when error page comes

            
    else:
        form = ContactUsForm()

    context['form'] = form
    
    return render(request, 'qr_generator/contact.html', context)




# Define function to download pdf file using template
def download_file(request, id='', file_type=''):


    if id != '':
        file = QRCollection.objects.get(id=id).qr_code
        obj = MEDIA_ROOT + '/' + str(file)


        match file_type:
            case 'pdf':
                filepath, filename = convert_to_pdf(obj)
            
            case 'png':
                filepath, filename = convert_to_png(obj)

            case 'jpg':
                filepath, filename = convert_to_jpg(obj)

            case 'svg':
                filepath, filename = convert_to_svg(obj)
            
            case 'jpeg':
                filepath, filename = convert_to_jpeg(obj)

        path = open(filepath, 'rb')
        mime_type, _ = mimetypes.guess_type(filepath)
        response = HttpResponse(path, content_type=mime_type)
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        return response

def learn_more(request):
    return render(request, 'base/coming_soon.html')

def page_not_found(request, exception):
    return render(request, 'base/error404.html', status=404)

qr_gen_project/templates/qr_generator/common/phone_qr.html
{% extends 'qr_generator/index.html' %}

{% load static %}

  {% block style %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'qr_generator/js/custom/generateqr.js' %}"></script>
    <link rel="stylesheet" href="{% static 'qr_generator/css/generateqr.css' %}" />
  {% endblock style %}

  {% block title %}|&nbsp;Generate QR{% endblock title %}
  
  {% block content %}

    
    <div class="wrapper">
      
      <div class="container">
        
        <div class="box1">
          <h2>Choose a Feature</h2>
          <div class="cards" id="menu">
            <div class="card1">
              <button type="button" href="#p1">
                <i class="uil uil-link"></i>URL/Link
              </button>
              <button type="button" href="#p2">
                <i class="uil uil-google-play"></i>App Store
              </button>
              <button type="button" href="#p3">
                <i class="uil uil-file-alt"></i>Text
              </button>
              <button type="button">
                <i class="uil uil-share-alt"></i>Socials
              </button>
            </div>

            <div class="card2">
              <button type="button">
                <i class="uil uil-envelope-alt"></i>Email
              </button>
              <button type="button">
                <i class="uil uil-paypal"></i>Paypal
              </button>
              <button type="button" href="#p4">
                <i class="uil uil-file-plus"></i>PDF
              </button>
              <button type="button" href="#p5">
                <i class="uil uil-github-alt"></i>Github
              </button>
            </div>

            <div class="card3">
              <button type="button">
                <i class="uil uil-users-alt"></i>Vcard
              </button>
              <button type="button" href="#p7">
                <i class="uil uil-dollar-alt"></i>Bank details
              </button>
              <button type="button" href="#img">
                <i class="uil uil-image-v"></i>Image
              </button>
              <button type="button">
                <i class="uil uil-whatsapp"></i>Whatsapp
              </button>
            </div>

            <div class="card4">
              <button type="button" href="#p8">
                <i class="uil uil-phone-volume"></i>Phone
              </button>
              <button type="button">
                <i class="uil uil-bitcoin-circle"></i>Bitcoin
              </button>
              <button type="button"><i class="uil uil-music"></i>Music</button>
              <button type="button"><i class="uil uil-wifi"></i>Wifi</button>
            </div>

            <div class="card5">
              <button type="button" href="#p6">
                <i class="uil uil-video"></i>Zoom
              </button>
              <button type="button" href="#p9">
                <i class="uil uil-favorite"></i>Rating
              </button>
              <button type="button">
                <i class="uil uil-calender"></i>Event
              </button>
              <button type="button">
                <i class="uil uil-location-point"></i>Location
              </button>
            </div>
          </div>

          <div class="content">
            <div class="page active" id="p1">
              <!-- <section id="url"> -->
                <p class="title">Enter URL or Link</p>
                <form action="{% url 'qr_generator:generate_qr' %}" method="post" id="url-input">
                  {% csrf_token %}
                  <input type="url" placeholder="Input URL/Link" name="url-link" required/>
                </form>
                <button type="submit" form="url-input">Generate QR Code</button>
              <!-- </section> -->
            </div>

            <div class="page" id="p2">
              <!-- <section id="store"> -->
              <p class="title">Enter URL or Link</p>
              <form action="{% url 'qr_generator:generate_qr' %}" method="post" id="app-store">
                {% csrf_token %}
                <input type="url" placeholder="Enter Link to Application" name="text" required/>
              </form>
              <button type="submit" form="app-store">Generate QR Code</button>
                

              <!-- </section> -->
            </div>
            <div class="page" id="p3">
              <!-- <section id="store"> -->
              <p class="title">Enter a Text</p>
              <form action="{% url 'qr_generator:generate_qr' %}" method="post" id="text-input">
                {% csrf_token %}
                <textarea name="text" id="message"></textarea>
              </form>
              <button type="submit" form="text-input">Generate QR Code</button>
              <!-- </section> -->
            </div>
       
            <div class="page" id="p5">
              <!-- <section id="store"> -->
              <p class="title">Github</p>
              <form action="{% url 'qr_generator:generate_qr' %}" method="post" id="github-input">
                {% csrf_token %}
              <input type="url" placeholder="Input your github url" name="text"/>
              </form>
              <button type="submit" form="github-input">Generate QR Code</button>
              <!-- </section> -->
            </div>
            <div class="page" id="p6">
              <!-- <section id="store"> -->
              <p class="title">Zoom Link</p>
              <form action="{% url 'qr_generator:generate_qr' %}" method="post" id="zoom-input">
                {% csrf_token %}
                <input type="url" placeholder="Enter Zoom Link" name="text"/>
                </form>
                <button type="submit" form="zoom-input">Generate QR</button>
              <!-- </section> -->
            </div>
            <div class="page" id="p7">
              <!-- <section id="store"> -->
              <p class="title">Bank Details</p>
              <form action="" method="post">
              <input type="text" placeholder="Bank name" />
              <input type="text" placeholder="Full Name" />
              <input type="text" placeholder="Account Number" />
            </form>
              <!-- </section> -->
            </div>
            <div class="page" id="p8">
              <!-- <section id="store"> -->
              <p class="title">Phone Details</p>
              <form action="" method="post"></form>
                <input type="number" placeholder="Country Code" />
                <input type="number" placeholder="Phone Number" />
              
              <!-- </section> -->
            </div>
            <div class="page" id="p9">
              <!-- <section id="store"> -->
              <p class="title">Ratings</p>
              <input type="number" placeholder="Enter ratings page link" />
              <!-- </section> -->
            </div>


            <div class="page" id="p4">
              <!-- <section id="store"> -->
              <p class="title">Coming soon</p>
              
              <!-- </section> -->
            </div>

            <div class="page" id="img">
              <!-- <section id="store"> -->
              <p class="title">Coming soon...</p>
              
              <!-- </section> -->
            </div>


          </div>
        </div>
        <div class="box2">

          
          {% if qr_image %}
          <div class="qrimage">
            <img src="{{ qr_image.qr_code.url }}" name=img value="{{ qr_image }}" alt="qr code image" />
          {# Then save #}

          <button type="submit" class="btn2"><i class="uil uil-import"></i><a href={% url 'qr_generator:save_qr' id=qr_image.id %}>Save</a></button>
          <button class="btn2"><i class="uil uil-share-alt"></i><a href={% url 'qr_generator:share'  'qr_image.image.url' %}>Share</a></button>   
            <select  class="btn2" id=downLoad_option name="download_option" onchange="location = this.value;">
              <option value="">--Download--</option>
              <option value="{% url 'qr_generator:download' qr_image.id 'pdf' %}">PDF</option>
              <option value="{% url 'qr_generator:download' qr_image.id 'png' %}">PNG</option>
              <option value="{% url 'qr_generator:download' qr_image.id 'svg' %}">SVG</option>
              <option value="{% url 'qr_generator:download' qr_image.id 'jpeg' %} ">JPEG</option>
              <option value="{% url 'qr_generator:download' qr_image.id 'jpg'%} ">JPG</option>
            </select>
            

          
            {% else %}
            <img src="{% static 'qr_generator/images/qrcodeimg.png'%}" alt="qr code image" width="70%" height="60%" title="This is A SAMPLE"/>
            
            
          {% endif %}
          {# and a text here to tell it's a description#}
         
        </div>
      </div>
    </div>
    {% block extra_script %}
    {% endblock extra_script %}

    {% endblock content %}
    {% block top_footer %}{% endblock top_footer %}
    {% block middle_footer %}{% endblock middle_footer %}