qr_gen_project/accounts/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



app_name = 'accounts'
urlpatterns = [
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html', ), name='password_reset_done', ),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), name='password_reset_confirm'),
]

urlpatterns += [

    path('', views.index, name="index"),
    path('register/',views.register, name="register"),
    path('login/',views.login_view, name="login"),
    path('logout/', auth_views.LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    path('dashboard/',views.dashboard, name="dashboard"),
    path('faq/', views.faq, name="faq"), # avong added thisn for FAQ page
]

qr_gen_project/api/urls.py
from django.urls import include, path,re_path
from api import views


urlpatterns = [
    path('register/', views.RegisterAPIView.as_view(), name = 'register'),
    path('login/', views.LoginAPIView.as_view(), name = 'login'),
    path('user/', views.AuthUserAPIView.as_view(), name = 'user'),
]

urlpatterns += [
    path('<str:category>', views.QRCategoryView.as_view(), name='qr_category'), # Fetch all user QR from a category
    path('<str:category>/<int:pk>', views.QROneCategoryView.as_view(), name='get_one'), # Fetch one user QR from a category
    path('', views.QRAPIView.as_view(), name='all_user_qr'), # Fetch all user QR
]

# Coming soon ...
# urlpatterns = [
#     path('<int:id>/delete', views.DeleteQRAPIView.as_view(), name='delete_one'), # Delete One user QR from a category    
#     path('<int:id>/category/create/', views), # Create a new QR in a category ... coming soon
#     path('<int:id>/category/edit/', views), # edit a QR in a category ... coming soon
#     path('<int:id>/<str:category/delete', views.), # Delete all user QR from a category
#     path('<str:category>/<int:id>/delete', views.DeleteQRAPIView.as_view(), name='delete_one'), # Delete One user QR from a category
#     path('<int:id>/delete', views.), # Delete all user QR from all categories
# ]

qr_gen_project/qr_gen_project/urls.py
# qr_gen_project/settings.py

from re import M
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


from django.contrib.auth import views as auth_views

schema_view = get_schema_view(
   openapi.Info(
      title="QR Planets API Documentation",
      default_version='v1',
      description="""The Easiest Way to generate, download &amp; share QR Codes Online with QR Planet Code Generator within few minutes.
      Get started today.
      These are the Available Endpoints, Other API Endpoints are coming soon""",
      
      contact=openapi.Contact(email="simplenick01@gmail.com"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
   authentication_classes=[]
)


urlpatterns = [
   path('qr-gen/api/documentation/', schema_view.with_ui('swagger', cache_timeout=0), name='docs'),
   path('qr-gen/api/redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
   path('qr-gen/api/', include('api.urls'), ),
]

urlpatterns += [
    path('qr-gen/', include('qr_generator.urls', namespace='qr_generator'),),
    path('qr-gen/admin/', admin.site.urls),
]

urlpatterns += [
    path('qr-gen/accounts/', include('accounts.urls', namespace='accounts'),),
]

urlpatterns +=[
    path('reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'), name='password_reset_complete'),      
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "qr_generator.views.page_not_found"

qr_gen_project/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin

from django.contrib.auth.validators import UnicodeUsernameValidator

from django.utils.translation import gettext_lazy as _
from django.utils import timezone

import jwt
from django.conf import settings
from datetime import datetime, timedelta

class UsersManager(UserManager):
    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError("The given username must be set")

        if not email:
            raise ValueError("The given email must be set")

        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(username, email, password, **extra_fields)


class QRUser(AbstractBaseUser, PermissionsMixin):
    """We are Using Email as our ID"""
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )

    email = models.EmailField(_("email address"), blank=False, unique=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)
    email_verified = models.BooleanField(
        _("active"),
        default=False,
        help_text=_(
            "Designates whether this user's email is verified"
        ),
    )

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
   
    objects=UsersManager()

    @property
    def token(self):
        """Generate a token for the User using JWT"""
        token = jwt.encode(
            {
                'username': self.username,
                'email': self.email,
                'exp': datetime.utcnow() + timedelta(hours=24),
                },

                settings.SECRET_KEY,
                algorithm='HS256'
            )

        return token

qr_gen_project/accounts/forms.py
from .models import QRUser
from django.contrib.auth.forms import UserCreationForm
from django import forms


class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = QRUser
        fields = ('username', 'email', 'password1', 'password2')
       

    # def clean(self):
    #     value = self.cleaned_data['fullname']
    #     if not value:
    #         return 'Name Empty'
    #     # Do some cleaning later
    #     return value

    def save(self, commit=True):
        user = super(CreateUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

qr_gen_project/accounts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from accounts.decorators import unauthenticated_user
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout, authenticate

from .forms import CreateUserForm

#===============================================================
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm

from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes


from django.contrib.auth import get_user_model


User = get_user_model()


def index(request):
    return render(request, 'accounts/index.html')


# Registers a new user
#@unauthenticated_user
def register(request):

	template = 'accounts/register.html'
		
	if request.method=='POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			form.save()
			email = form.cleaned_data.get('email')
			password = form.cleaned_data.get('password1')
			user = authenticate(request, email=email, password=password)
		
			login(request, user)
			messages.success(request," Account was Created for "+email)
			return redirect('qr_generator:home')
		
		else:
			messages.error(request, 'Incorrect credentials')

		
	form = CreateUserForm()
			
	context = {'form':form}
	return render(request, template, context)




@unauthenticated_user
def login_view(request):
	""" This uses the built in Django User"""
	context = {}

	if request.method =='POST':
		username = request.POST.get('username')
		email = request.POST.get('email')
		password = request.POST.get('password')

		user = authenticate(request, email=email, password=password)

		if user is not None:
			login(request, user)
			messages.success(request, f"You are now logged in as {email}.")
			return redirect('qr_generator:home',) # pk=str(request.user.id)
		
		else: 
			messages.error(request, 'Account not Registered!!')
	
	return render(request, 'accounts/login.html', context)


@login_required(login_url="/qr-gen/accounts/login")
def dashboard(request):
	context = {}
	return redirect('qr_generator:home')


@login_required(login_url="/qr-gen/accounts/login")
def log_out(request):
	logout(request)
	messages.success(request, f'{request.user} Logged out')
	return redirect(to='qr_generator:home')


def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)

		if password_reset_form.is_valid():
			email = password_reset_form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=email))

			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"

					email_template = "accounts/password/password_reset_email.txt"

					extra = {
					"email":user.email,
					'domain':'127.0.0.1:8000',#!
					'site_name': 'QR Planet',#!
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',#!
					}

					email = render_to_string(email_template, extra)
					
					try:
						send_mail(subject, email, 'simplenick01@gmail.com',[user.email,], fail_silently=False) #! change admin later
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
					return redirect ('accounts:password_reset_done')#!
	password_reset_form = PasswordResetForm()
  
	return render(request=request, template_name="accounts/password/password_reset.html", context={"password_reset_form":password_reset_form},)

# added the faq view
@login_required(login_url="/accounts/login")
def faq(request):
    return redirect(request, 'accounts:faq')

qr_gen_project/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="keywords" content="qr code generator" />
        <meta name="description" content="The Easiest Way to generate, download &amp; share QR Codes
        Online with QR Planet Code Generator within few minutes. Get started today."/>
        <meta content="yes" name="apple-mobile-web-app-capable" />
        <meta itemprop="description" content="Quickly Generate, Download and Share QR Codes!"/>
        <title>Qr Planet</title>
        <link rel="icon" sizes="192x192" href="{% static 'base/favicon_io/android-chrome-192x192.png' %}"/>
        <link rel="apple-touch-icon" type="image/png" href="{% static 'base/favicon_io/apple-touch-icon.png' %}"/>
        <link rel="icon" type="image/png" sizes="512x512" href="{% static 'base/favicon_io/android-chrome-512x512.png' %}"/>
        <link rel="shortcut icon" href="{% static 'base/favicon_io/favicon.ico' %}" type="image/x-icon"/>
        <link rel="stylesheet" href="{%  static 'accounts/css/homepage.css' %}"/>
        <link rel="stylesheet" href="{% static 'accounts/css/faq.css' %}">
        <link rel="stylesheet" href="{% static 'accounts/css/fonts.css' %}">
    </head>
    
      <body>
        <header>
          <!-- <div class="wrapper"> -->
          <div class="inner-header">
            <a href="{% url 'accounts:index' %}"><img class="logo" src="{% static 'accounts/images/logo.svg' %}" alt="logo" /></a>
            <nav>
              <ul class="nav_links">
                <li><a href="{% url 'accounts:index' %}">Home</a></li>
                <li><a href="#">QR code</a></li>
                <li><a href="#">Why us?</a></li>
                <li><a href="#">API</a></li>
                <li><a href="#">Contact</a></li>
              </ul>
              {% if request.user.is_authenticated %}
              <button type = "submit" href="{% url 'accounts:dashboard' %}" class="Secondary-button">Dashboard</button>
              <button type = "submit" href="{% url 'accounts:logout' %}" class="Primary-button">Logout</button>
              {% else %}
              <button type = "submit" href="{% url 'accounts:login' %}" class="Secondary-button">Login</button>
              <button type = "submit" href="{% url 'accounts:register' %}" class="Primary-button">Get started</button>
              {% endif %}
          </div>
        </nav>
        </header>

    <!-- header end-->
{% block content %}

{% endblock %}
</body>
<footer>
    <div class="main_footer">
      <div class="top_footer">
        <div>
          <h4>Don't miss out!</h4>
          <p>Do you like discounts, specials offers and rewards?</p>
        </div>
          <form>        
            <input type="email" class="mail" placeholder="Email" class="">          
            <button type="submit" class="footer-button">Subscribe Now </button>
          </form>
      </div>    
      </div> <hr>

      <div class="middle_footer">
        <p class="md_footer_info">Enjoy seamless and efficient generation of qr codes. Create various styles for your qr codes using the various designs available</span></p>
        <div class="footer_info">
          <p>QR Planet</p>
          <ul>
            <li><a href="#">How to generate QR codes</a></li>
            <li><a href="#">Dynamic QR codes</a></li>
            <li><a href="#">Static QR codes</a></li>
          </ul>
        </div>

        <div class="footer_info">
            <p>Why us?</p>
          <ul>
            <li>Product features</li>
            <li>About us</li>
            <li>FAQs</li>
        </div>
        <div class="footer_info">
          <p>API</p>
          <ul>
            <li>API docs</li>
          </ul>
        </div>      
        <div class="footer_info">
          <p>Contact</p>
          <!-- <div class="socials"> -->
          <img src="{% static 'accounts/images/Twitter.png' %}" alt="Twitter" height="24px"/>
          <img src="{% static 'accounts/images/Facebook.png' %}" alt="Facebook" height="24px" />
          <img src="{% static 'accounts/images/Linkedin.png' %}" alt="Linkedin" height="24px" />
        <!-- </div> -->
    </div>
  </div>
    <hr>  
  <div class="bottom_footer">
      <div class="footer_2">
        <p><span>2022 </span> QR Planet; All Rights Reserved</p>      
        <a href="#">Report</a>
      </div>

  </div>

  </footer>

</html>

qr_gen_project/templates/accounts/dashboard.html
{% extends 'accounts/base.html' %}

{% block content %}
    <div class="container">
        <h2>{{user.username}}</h2>
        <h2>{{user.email}}</h2>
    </div>
{% endblock %}

qr_gen_project/templates/accounts/faq.htm
{% extends 'accounts/base.html' %}

{% block content %}
<div class="background">
    <!-- <img src="background.svg" alt="background"> -->
    <div class="question">
      <h4>Have a question</h4>

      <span class="span">?</span>
    </div>
    <div class="text">
      Browse our knowledge base below or use the button below to send a custom
      message
    </div>

    <div class="big">


      <div class="FAQ1">
        <h4 class="faq-text1">
          Is QR Planet free?
          <span><a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="500px"
              height="530px" color="#87a1c9" viewBox="0 0 448 512"
              class="svg"><path color="#87a1c9" d="M432 256c0 17.69-14.33
                32.01-32 32.01H256v144c0 17.69-14.33 31.99-32
                31.99s-32-14.3-32-31.99v-144H48c-17.67
                0-32-14.32-32-32.01s14.33-31.99 32-31.99H192v-144c0-17.69
                14.33-32.01 32-32.01s32 14.32 32 32.01v144h144C417.7 224 432
                238.3 432 256z" /></svg></span>
          </h4>
        </div>

        <div class="FAQ1">
          <h4 class="faq-text1">
            Is the API easily integratable? <span><svg
                xmlns="http://www.w3.org/2000/svg" width="500px"
                height="500px" color="#87a1c9" viewBox="0 0 448 512"
                class="svg"><path color="#87a1c9" d="M432 256c0 17.69-14.33
                  32.01-32 32.01H256v144c0 17.69-14.33 31.99-32
                  31.99s-32-14.3-32-31.99v-144H48c-17.67
                  0-32-14.32-32-32.01s14.33-31.99 32-31.99H192v-144c0-17.69
                  14.33-32.01 32-32.01s32 14.32 32 32.01v144h144C417.7 224 432
                  238.3 432 256z" /></svg></span>
            </h4>

          </div>
        </div>

        <div class="big">


          <div class="FAQ1">
            <h4 class="faq-text1">
              Who can use QR Planet? <span><svg
                  xmlns="http://www.w3.org/2000/svg" width="500px"
                  height="500px" color="#87a1c9" viewBox="0 0 448 512"
                  class="svg"><path color="#87a1c9" d="M432 256c0 17.69-14.33
                    32.01-32 32.01H256v144c0 17.69-14.33 31.99-32
                    31.99s-32-14.3-32-31.99v-144H48c-17.67
                    0-32-14.32-32-32.01s14.33-31.99 32-31.99H192v-144c0-17.69
                    14.33-32.01 32-32.01s32 14.32 32 32.01v144h144C417.7 224
                    432 238.3 432 256z" /></svg></span>
              </h4>

            </div>

            <div class="FAQ1">
              <h4 class="faq-text1">
                Is QR Planet secure? <span><svg
                    xmlns="http://www.w3.org/2000/svg" width="500px"
                    height="520px" color="#87a1c9" viewBox="0 0 448 512"
                    class="svg"><path color="#87a1c9" d="M432 256c0
                      17.69-14.33 32.01-32 32.01H256v144c0 17.69-14.33
                      31.99-32 31.99s-32-14.3-32-31.99v-144H48c-17.67
                      0-32-14.32-32-32.01s14.33-31.99
                      32-31.99H192v-144c0-17.69 14.33-32.01 32-32.01s32 14.32
                      32 32.01v144h144C417.7 224 432 238.3 432 256z" /></svg></span>
                </h4>

              </div>
            </div>

            <div class="big">


              <div class="FAQ1">
                <h4 class="faq-text1">
                  Can the QR codes gernerated
                  be used commercially? <span><svg
                      xmlns="http://www.w3.org/2000/svg" width="500px"
                      height="520px" color="#87a1c9" viewBox="0 0 448 512"
                      class="svg"><path color="#87a1c9" d="M432 256c0
                        17.69-14.33 32.01-32 32.01H256v144c0 17.69-14.33
                        31.99-32 31.99s-32-14.3-32-31.99v-144H48c-17.67
                        0-32-14.32-32-32.01s14.33-31.99
                        32-31.99H192v-144c0-17.69 14.33-32.01 32-32.01s32
                        14.32 32 32.01v144h144C417.7 224 432 238.3 432 256z"
                        /></svg></span>
                  </h4>

                </div>

                <div class="FAQ1">
                  <h4 class="faq-text1">
                    Is there any restriction to
                    use of QR codes? <span><svg
                        xmlns="http://www.w3.org/2000/svg" width="500px"
                        height="550px" color="#87a1c9" viewBox="0 0 448 512"
                        class="svg"><path color="#87a1c9" d="M432 256c0
                          17.69-14.33 32.01-32 32.01H256v144c0 17.69-14.33
                          31.99-32 31.99s-32-14.3-32-31.99v-144H48c-17.67
                          0-32-14.32-32-32.01s14.33-31.99
                          32-31.99H192v-144c0-17.69 14.33-32.01 32-32.01s32
                          14.32 32 32.01v144h144C417.7 224 432 238.3 432 256z"
                          /></svg></span>
                    </h4>

                  </div>
                </div>

              </div>
{% endblock %}

qr_gen_project/templates/accounts/login.html
{% extends 'qr_generator/index.html'%}

{% load static%}

{% block style %}
    <link rel="stylesheet" href="{% static 'accounts/css/Login.css'%}">
{% endblock style %}

{% block title %} {{ block.super }}&nbsp;&#124;&nbsp;Login {% endblock title %}
{% block content %}

<div class="container">
    <div class="mobile-logo">
      <img src="{% static 'accounts/images/mobile_logo.png'%}" alt="Logo" />
    </div>
    <div class="forms">
      <div class="form login">
        <p class="title">Welcome</p>
        <p class="sub-title">We're happy to have you back</p>
        <form action="{% url 'accounts:login' %}" method="post">
            {% csrf_token%}
          <div class="input-field">
            <input type="text" id="email" name="email" placeholder="Enter your email" required />
            <i class="uil uil-envelope icon"></i>
          </div>
          <div class="input-field">
            <input
              type="password"
              name="password"
              id="password"
              placeholder="Enter your password"
              required
            />
            <!-- <i class="uil uil-lock icon"></i> -->
            <i class="uil uil-eye-slash showHidePw"></i>
          </div>

          <div class="checkbox-text">
            <div class="checkbox-content">
              <input type="checkbox" id="logCheck" checked/>
              <label for="logCheck" class="text">Keep me logged in</label>
            </div>

            <a href="{% url 'accounts:password_reset'%}" class="text">Forgot password?</a>
          </div>

          <div class="input-field button">
            <input type="submit" value="Login" required />
          </div>
        </form>

        <div class="login-signup">
          <span class="text"
            >Not yet registered&quest;
            <a href="{% url 'accounts:register'%}" class="text signup-text">Sign Up</a>
          </span>
        </div>
      </div>
    </div>
  </div>

  <script src="{% static 'accounts/js/custom/validate_login.js' %}"></script>

</script>
<script>
    var form_fields = document.getElementsByTagName("input");
    form_fields[2].placeholder = "Enter your Email...";
    form_fields[3].placeholder = "Enter Your Password...";

    for (var field in form_fields) {
    form_fields[field].className += " form-control";
    }
</script>

{% endblock content%}


{# Override top and middle footer#}

{% block top_footer %}{% endblock top_footer %}
{% block middle_footer %}{% endblock middle_footer %}

qr_gen_project/templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>You have been Logged out</h1>
        <h5><a href="{% url 'accounts:login' %}">Login In Again</a></h5>
    </div>
{% endblock %}

qr_gen_project/templates/accounts/register.html
{% extends 'qr_generator/index.html'%}

{% load static%}

{% block style %}
    <link rel="stylesheet" href="{% static 'accounts/css/Login.css'%}">
{% endblock style %}

{% block title %} {{ block.super }}&nbsp;&#124;&nbsp;Sign&nbsp;Up&nbsp;{% endblock title %}

{% block content %}

<div class="container">
  <div class="mobile-logo">
    <img src="{% static 'accounts/images/mobile_logo.png'%}" alt="Logo" />
  </div>
  <div class="forms">
    <div class="form login">
      <p class="title">Sign Up</p>
      <p class="sub-title">Please fill in this form to create an account</p>
      <form action="{% url 'accounts:register'%}" method="post">
        {% csrf_token %}
        <div class="input-field">
          {{ form.username }}
        </div>
        <div class="input-field">
          {{form.email}}
          <i class="uil uil-envelope icon"></i>
        </div>
        <div class="input-field">
          {{form.password1}}
          <i class="uil uil-eye-slash showHidePw"></i>
        </div>
        <div class="input-field">
          {{form.password2}}
          <i class="uil uil-eye-slash showHidePw"></i>
        </div>

        <div class="checkbox-text">
          <div class="checkbox-content">
            <input type="checkbox" id="logCheck" />
            <label for="logCheck" class="text"
              >I accept the
              <a href="#">Terms of use & Privacy Policy</a></label
            >
          </div>
        </div>

        <div class="input-field button">
          <input type="submit" value="Sign Up" required />
        </div>
      </form>

      <div class="login-signup">
        <span class="text"
          >Already have an account?
          <a href="{% url 'accounts:login'%}" class="text signup-text">Login</a>
        </span>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'accounts/js/custom/validate_registration.js' %}"></script>
<script>
    var form_fields = document.getElementsByTagName("input");
    form_fields[2].placeholder = "Enter a Username..";
    form_fields[3].placeholder = "Enter your Email..";
    form_fields[4].placeholder = "Enter your password...";
    form_fields[5].placeholder = "Confirm your password...";
    
    for (var field in form_fields) {
    form_fields[field].className += " form-control";
    }
    </script>

{% endblock content%}

{# Override top and middle footer#}

{% block top_footer %}{% endblock top_footer %}
{% block middle_footer %}{% endblock middle_footer %} 